image: python:latest

#include:
    #- template: Security/SAST.gitlab-ci.yml
    #- template: Security/Secret-Detection.gitlab-ci.yml

#variables:
    #SAST_EXCLUDED_PATHS: unit_tests.py

stages:
    #- build
    - test
    - package

.unitTest:
    stage: test
    before_script:
        - pip install flask
        - pip install pytest
    script:
        - py.test unit_tests.py

buildPackage:
    stage: package
    before_script:
        - pip install twine
    script:
        - mkdir calcyoulater2
        - ls | grep -v calcyoulater2 | xargs mv -t calcyoulater2
        - mkdir calcyoulaterpkg2
        - mv calcyoulater2/ calcyoulaterpkg2/calcyoulater2
        - cd calcyoulaterpkg2 && cd calcyoulater2
        - mv server.py __init__.py
        - mv -t ../ setup.py MANIFEST.in
        - cd ..
        - pip install setuptools wheel
        - python setup.py sdist bdist_wheel
        - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url $ 
          {CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
         