image: python:3.11

stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: ""

dockerize_package:
  stage: build
  image: docker:20.10.24
  services:
    - docker:20.10.24-dind
  before_script:
    - apt-get update && apt-get install -y curl grep sed bash
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - export PACKAGE_VERSION=$(grep -m1 version setup.py | sed "s/.*version=['\"]\([^'\"]*\)['\"].*/\1/")
  script:
    - echo "📦 Building Docker image for version $PACKAGE_VERSION"
    - docker build \
        --build-arg PAT_NAME=__token__ \
        --build-arg PAT_VALUE=$TWINE_PASSWORD \
        --build-arg PACKAGE_VERSION=$PACKAGE_VERSION \
        -t $CI_REGISTRY_IMAGE:$PACKAGE_VERSION .
    - docker push $CI_REGISTRY_IMAGE:$PACKAGE_VERSION