image: python:latest

#include:
    #- template: Security/SAST.gitlab-ci.yml
    #- template: Security/Secret-Detection.gitlab-ci.yml

#variables:
    #SAST_EXCLUDED_PATHS: unit_tests.py

stages:
    #- build
    - test
    - package
    - build

.unitTest:
    stage: test
    before_script:
        - pip install flask
        - pip install pytest
    script:
        - py.test unit_tests.py

.buildPackage:
    stage: package
    before_script:
        - pip install twine
    script:
        - mkdir calcyoulater2
        - ls | grep -v calcyoulater2 | xargs mv -t calcyoulater2
        - mkdir calcyoulaterpkg2
        - mv calcyoulater2/ calcyoulaterpkg2/calcyoulater2
        - cd calcyoulaterpkg2 && cd calcyoulater2
        - mv server.py __init__.py
        - mv -t ../ setup.py MANIFEST.in
        - cd ..
        - pip install setuptools wheel
        - python setup.py check --metadata --strict
        - python setup.py sdist bdist_wheel
        - ls -lh dist/

        - curl -I ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi || true
        
        - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*

buildContainer:
    stage: build
    image: docker:20.10.24
    variables:
        IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    services:
        - docker:20.10.24-dind
    before_script:
        - docker pull curlimages/curl
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
        - docker build --build-arg PAT_NAME=$PAT_NAME --build-arg PAT_VALUE=$PAT_VALUE -t $IMAGE_TAG .
        - docker image ls
        - docker run --interactive -p 5000:5000 --name flask-test $IMAGE_TAG &
        - sleep 10
        - docker ps
        - container_ip=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' flask-test)
        - container_ip_port="${container_ip}:5000"
        - docker run --rm curlimages/curl -L -v $container_ip_port
        #UPDATED
